services:
  mpcb-ssh:
    build: .
    ports:
      - "8882:3000"
    volumes:
      - mpcb-ssh-data:/app/data
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - DB_PATH=/app/data/db.sqlite
      - TELEGRAM_SERVICE_BOT_TOKEN=${TELEGRAM_SERVICE_BOT_TOKEN}
    restart: unless-stopped

volumes:
  mpcb-ssh-data:
